[tool.poetry]
authors = ["Vagiz Duseev <vagiz.duseev@dynatrace.com>"]
description = "Dynatrace Extensions YAML Assembler"
documentation = "https://github.com/dynatrace-extensions/dt-extensions-yaml-assembler"
homepage = "https://github.com/dynatrace-extensions/dt-extensions-yaml-assembler"
keywords = ["dynatrace", "cli", "extensions"]
license = "Apache-2.0"
maintainers = ["Vagiz Duseev <vagiz.duseev@dynatrace.com>"]
name = "dt-extensions-yaml-assembler"
packages = [
  {include = "yaml_assembler"},
]
readme = "README.md"
repository = "https://github.com/dynatrace-extensions/dt-extensions-yaml-assembler"
version = "0.1.0"

[tool.poetry.dependencies]
PyYAML = "^6.0"
python = "^3.8"
wheel = "^0.37"
jsonschema = "^4.7"
typer = "^0.6"
typing-extensions = "^4.10.0"
ruamel-yaml = "^0.18.6"

[tool.poetry.group.dev.dependencies]
black = {version = ">=20", allow-prereleases = true}
bump2version = ">=1.0"
types-PyYAML = ">=5.4"
types-jsonschema = ">=3.2"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.8"]

[tool.poetry.scripts]
assemble-yaml = 'yaml_assembler.cli:app'

[tool.black]
line-length = 120
